name: Publish NPM Package

description: Publish to npm and GitHub packages.

inputs:
  github_token:
    description: GitHub token to authenticate with. Must have push + release permissions.
    required: true

  npm_token:
    description: NPM token to authenticate with.
    required: true

runs:
  using: composite
  steps:
    - uses: actions/setup-node@v4
      with:
        registry-url: 'https://registry.npmjs.org'

    - run: npm publish --access public
      shell: bash
      env:
        NODE_AUTH_TOKEN: ${{ inputs.npm_token || env.npm_token }}

    - uses: actions/setup-node@v4
      with:
        registry-url: 'https://npm.pkg.github.com'
        scope: '@${{ github.repository_owner }}'

    - run: npm publish
      shell: bash
      env:
        NODE_AUTH_TOKEN: ${{ inputs.github_token || env.github_token }}
