name: Semantic Version Bump
description: Bumps the package.json version according to semver, with beta components, and pushes it back to the repository

inputs:
  path:
    description: Path to package
    required: true
    default: ./
  prerelease_id:
    description: If prerelease bump is required, the name of the prerelease id.
    required: true
    default: next
  prerelease:
    description: If true, the version is bumped to the next prerelease, with the prerelease id set in `prerelease_branch`.
    required: false
    default: 'false'

outputs:
  previous:
    description: The previous semantic version.
  next:
    description: The next semantic version.
  has_changed:
    description: Whether the version has changed since the previous.

runs:
  using: node20
  main: dist/index.js
