name: Publish GitHub Release
description: Pushes any commits back to the main branch and creates a GitHub release with the latest tag

inputs:
  github_token:
    description: GitHub token to authenticate with. Must have push + release permissions.
    required: true

  main_branch:
    description: The name of the main branch
    required: true
    default: main

  body_path:
    description: The path to the file to populate the release body with
    required: true
    default: CHANGELOG.md

  asset_paths:
    description: Newline seperated list of globs/path to assets to be uploaded
    required: false

outputs:
  id:
    description: The release id

  upload_url:
    description: The URL to upload assets to the release

  html_url:
    description: The URL to the release

  assets_url:
    description: The URL to the release assets

runs:
  using: node12
  main: dist/index.js
