name: Publish Docker Image

description: Build and push Docker image to DockerHub and GitHub Packages

inputs:
  github_actor:
    description: GitHub actor corresponding to the github_token.
    required: true

  github_token:
    description: GitHub token to authenticate with. Must have push + release permissions.
    required: true

  dockerhub_username:
    description: DockerHub username to authenticate with.
    required: true

  dockerhub_password:
    description: DockerHub password or token to authenticate with.
    required: true

  dockerhub_namespace:
    description: DockerHub namespace to publish images github_token.
    required: true

  docker_context:
    description: The Docker build context location.
    default: '.'

  docker_build_args:
    description: Any Docker build arguments, as a newline-separated list.

runs:
  using: composite
  steps:
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ inputs.dockerhub_username || env.dockerhub_password }}
        password: ${{ inputs.dockerhub_password || env.dockerhub_password }}

    - name: Log in to the Container registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ inputs.github_actor || env.github_actor }}
        password: ${{ inputs.github_token || env.github_token }}

    - name: Extract metadata (tags, labels) for Docker
      id: meta
      uses: docker/metadata-action@v3
      with:
        images: |
          ${{ inputs.dockerhub_namespace || env.dockerhub_namespace }}/${{ github.repository }}
          ghcr.io/${{ github.repository }}

    - name: Build and push Docker images
      uses: docker/build-push-action@v2
      with:
        context: ${{ inputs.docker_context || '.' }}
        build-args: ${{ inputs.docker_build_args }}
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
