name: Publish Release Branch
description: Publishes the current working directory as a release branch, using the current git tag

inputs:
  fixed_branch:
    description: If set, a fixed branch to publish to, such as gh-pages
    required: false

  release_branch_prefix:
    description: The prefix for any release branches
    required: true
    default: release

  gitignore:
    description: The contents to append to the existing `.gitignore`. This is useful to exclude patterns that are normally included in the `.gitignore` file, with the `!` negation operator.
    default: ''
    required: false

runs:
  using: node12
  main: dist/index.js
