name: Integrate Commits

description: Integrate commits back into the main branch by building on a side-branch and passing status checks.

inputs:
  github_token:
    required: true
    description: GitHub token to authenticate with. Must have push permissions.

  main_branch:
    required: true
    default: main
    description: The name of the main branch to push commits to.

  integration_branch:
    required: true
    default: integration
    description: The branch to push commits to and build before merging into the main branch.

runs:
  using: composite
  steps:
    - name: Push to integration branch
      shell: bash
      run: git push -u origin HEAD:${{ inputs.integration_branch }}

    - uses: WyriHaximus/github-action-wait-for-status@v1.4.0
      env:
        GITHUB_TOKEN: ${{ secrets.github_token }}

    - name: Push to main branch
      shell: bash
      run: |
        git checkout ${{ inputs.main_branch }}
        git merge ${{ inputs.integration_branch }}
        git push ${{ inputs.main_branch}} --follow-tags
