name: Next Release

on:
  workflow_dispatch:
  pull_request:
    types:
      - closed

jobs:
  publish:
    if: "${{ (github.event.pull_request.merged == true && contains(github.event.pull_request.labels.*.name, 'Release: Next')) || github.event_name != 'pull_request' }}"
    runs-on: ubuntu-20.04
    steps:
      - uses: shabados/actions/setup-git-identity@release/next
        with:
          user: Shabad OS Bot
          email: team@shabados.com

      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: shabados/actions/bump-version@release/next
        id: bump-version
        with:
          prerelease: next

      - uses: shabados/actions/generate-changelog@release/next
        with:
          amend_commit: ${{ steps.bump-version.outputs.has_changed == 'true' }}

      - uses: c-hive/gha-npm-cache@v1

      - run: npm install

      - run: npm run build

      - uses: shabados/actions/publish-github@release/next
        with:
          github_token: ${{ secrets.GH_BOT_TOKEN }}

      - uses: shabados/actions/publish-branch@release/next
        with:
          gitignore: |
            !dist/
