name: Release Latest

on:
  workflow_dispatch:

jobs:
  build-publish-release:
    uses: shabados/actions/.github/workflows/release.yml@main
    secrets:
      GH_BOT_TOKEN: ${{ secrets.GH_BOT_TOKEN }}
