name: Trigger Release

on:
  pull_request_target:
    types:
      - closed

jobs:
  trigger--latest-release:
    if: "${{ github.event.pull_request.merged == true && contains(github.event.pull_request.labels.*.name, 'Release: Latest') }}"
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/github-script@v4
        with:
          script: |
            github.repos.createDispatchEvent({
              event_type: 'release-latest',
              owner: context.repo.owner,
              repo: context.repo.repo,
            })

  trigger--next-release:
    if: "${{ github.event.pull_request.merged == true && contains(github.event.pull_request.labels.*.name, 'Release: Next') }}"
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/github-script@v4
        with:
          script: |
            github.repos.createDispatchEvent({
              event_type: 'release-next',
              owner: context.repo.owner,
              repo: context.repo.repo,
            })
